export const APPOINTMENT_CREATE = "APPOINTMENT_CREATE";
export const APPOINTMENT_TYPE_CREATE = "APPOINTMENT_TYPE_CREATE";
export const APPOINTMENT_CLIENT_ALL = "APPOINTMENT_CLIENT_ALL";
export const APPOINTMENT_PAID_ALL = "APPOINTMENT_PAID_ALL";
export const APPOINTMENT_REQUESTED_ALL = "APPOINTMENT_REQUESTED_ALL";
export const APPOINTMENT_EDIT = "APPOINTMENT_EDIT";
export const APPOINTMENT_DELETE = "APPOINTMENT_DELETE";
export const APPOINTMENT_GET = "APPOINTMENT_GET";
export const APPOINTMENT_ALLOW = "APPOINTMENT_ALLOW";
export const APPOINTMENT_JOIN = "APPOINTMENT_JOIN";
export const APPOINTMENT_GROUPING = "APPOINTMENT_GROUPING";
export const INVOICE_UPDATE = "INVOICE_UPDATE";
export const GET_REMINDERS_ALLOW = "GET_REMINDERS_ALLOW";
export const APPOINTMENT_ALLOW_MSG = "APPOINTMENT_ALLOW_MSG";
export const APPOINTMENT_OUT = "APPOINTMENT_OUT";

export const APPOINTMENT_ONE_ONE = "APPOINTMENT_ONE_ONE";
export const EMPTY_APPOINTMENT = "EMPTY_APPOINTMENT";
export const UPDATE_REMINDERS = "UPDATE_REMINDERS";

export const APPOINTMENT_ONALLOW = "APPOINTMENT_ONALLOW";
export const APPOINTMENT_MONTH = "APPOINTMENT_MONTH";
export const GET_APPOINTMENT_TYPE = "GET_APPOINTMENT_TYPE";
export const REQUEST_ALL = "REQUEST_ALL";
export const REQUEST_PROVIDER = "REQUEST_PROVIDER";
export const RECIPIENT_ALL = "RECIPIENT_ALL";
export const SENDER_ALL = "SENDER_ALL";
export const REGISTER_PROVIDER = "REGISTER_PROVIDER";
export const PROVIDERS_ID = "PROVIDERS_ID";
export const CLIENTS_ID = "CLIENTS_ID";
export const PROVIDER_INFO = "PROVIDER_INFO";
export const PROVIDER_PHOTO = "PROVIDER_PHOTO";
export const PROVIDER_FULL = "PROVIDER_FULL";
export const PROVIDER_MUSIC_BACKGROUND = "PROVIDER_MUSIC_BACKGROUND";
export const USER_DELETE = "USER_DELETE";
export const SHOW_FORGOT_PASSWORD = "SHOW_FORGOT_PASSWORD";
export const LOGIN_PROVIDER = "LOGIN_PROVIDER";
export const SHOW_RESET_PASSWORD = "SHOW_RESET_PASSWORD";
export const APPOINTMENT_ACCEPT = 'APPOINTMENT_ACCEPT';
export const APPOINTMENT_CANCEL = "APPOINTMENT_CANCEL";

export const SHARE_DOCUMENT = "SHARE_DOCUMENT";
export const RECENT_DOCUMENT = "RECENT_DOCUMENT";
/**
 * CLient List Show
 */
export const UPDATE_INFO = 'UPDATE_INFO';
/**
 * authentication handles
 */
export const SET_CURRENT_USER = "SET_CURRENT_USER";
/**
 * miscellaneous
 */
export const SHOW_SPINNING = "SHOW_SPINNING";
/**
 *  Article
 */
export const POST_ARTICLE = "POST_ARTICLE";
export const PUBLISHED_ALL = "PUBLISHED_ALL";
export const ARTICLES_ALL = "ARTICLES_ALL";
export const ARTICLE_DETAILS = 'ARTICLE_DETAILS';
export const ARTICLE_DELETE = "ARTICLE_DELETE";
export const CATEGORY_LIST = "CATEGORY_LIST";
export const UPDATE_ARTICLE = "UPDATE_ARTICLE";
export const ARTICLE_DETAILS_DISPLAY = "ARTICLE_DETAILS_DISPLAY";
export const CATEGORY_ADD = "CATEGORY_ADD";

export const FILE_UPLOAD = "FILE_UPLOAD";
export const FILE_UPLOAD_ERROR = "FILE_UPLOAD_ERROR";
export const GET_COMMENT_BYID = "GET_COMMENT_BYID";

export const SET_PRICING_PLANS = "SET_PRICING_PLANS";
export const SET_CURRENT_SUBSCRIPTION = "SET_CURRENT_SUBSCRIPTION";
export const SET_STRIPE_ACCOUNT_LINK = "SET_STRIPE_ACCOUNT_LINK";
/**
 * Messages
 */
/**
 * Messages
 */
export const MESSAGES_LIST = "MESSAGES_LIST";
export const MESSAGES_LIST_ERROR = "MESSAGES_LIST_ERROR";
export const MESSAGES = "MESSAGES";
export const CLIENT_CONNECTED = "CLIENT_CONNECTED";
export const MESSAGES_ONE_ERROR = "MESSAGES_ONE_ERROR";
export const MESSAGES_EDIT = "MESSAGES_EDIT";
export const LAST_MESSAGES = "LAST_MESSAGES";

export const USERS = "USERS";

/**
 * Invitation
 */
export const INVITE_USER = "INVITE_USER";

/**
 * Drag
 */
export const DRAG_UPDATE = "DRAG_UPDATE";
export const GET_DRAG = "GET_DRAG";

/**
 * Note
 * @type {string}
 */
export const POST_NOTE = "POST_NOTE";
export const GET_NOTE = "GET_NOTE";
export const UPDATE_NOTE = "UPDATE_NOTE";
export const DELETE_NOTE = "DELETE_NOTE";
export const GET_ONE_NOTE = "GET_ONE_NOTE";

export const PRACTICE_LIST = "PRACTICE_LIST";

/**
 * Invite via email or phone
 */
export const INVITE = "INVITE";

/**
 * chatbot
 */
export const CHATBOT_PAGE = "CHATBOT_PAGE";
export const CHATBOT_ADD = "CHATBOT_ADD";
export const CHATBOT_ADD_MESSAGE = "CHATBOT_ADD_MESSAGE";
export const CHATBOT_DELETE_MESSAGE = "CHATBOT_DELETE_MESSAGE";
export const CHATBOT_ERROR = "CHATBOT_ERROR";
export const GET_CHATBOT = 'GET_CHATBOT';
export const GET_REPLY = "GET_REPLY";
export const GET_FAIL = "GET_FAIL";

