export const SPECIAL_CATEGORIES = {
    addiction: 'Addiction Specialist',
    art: 'Art Therapist',
    certified: 'Certified Clinical Anxiety',
    treatment: 'Treatment Professional',
    sex: 'Certified Sex Therapist',
    trauma: 'Certified Trauma Specialist',
    clinical: 'Clinical Hypnotherapist',
    coach: 'Coach',
    consultant: 'Consultant',
    counselor: 'Counselor',
    pastoral: 'Board Certified Pastoral Counselor',
    dietitian: 'Dietitian',
    distance: 'Distance Credentialed Counselor',
    marriage: 'Marriage & Family Therapist',
    mental_health: 'Maternal Mental Health Specialist',
    mental_specialist: 'Mental Health Specialist',
    mental_therapist: 'Mental Health Therapist',
    nurse: 'Nurse Practitioner',
    occupational: 'Occupational Therapist',
    physical: 'Physical Therapist',
    play: 'Play Therapist',
    primary: 'Primary Health Care',
    psychiatrist: 'Psychiatrist',
    psychologist: 'Psychologist',
    psychotherapist: 'Psychotherapist',
    psychotherapy: 'Psychotherapy Practice',
    sexologist: 'Sexologist',
    social: 'Social Worker',
    speech: 'Speech Therapist',
};

export const FILTER_LIST = {
    acceptance_commitment: 'Acceptance and Commitment Therapy',
    adolescents: 'Adolescents',
    assessment: 'Assessment',
    chronic_illness_disability: 'Chronic Illness & Disability',
    cognitive_behavioral_therapy: 'Cognitive Behavioral Therapy',
    couples_marriage: 'Couples/Marriage',
    eating_disorders: 'Eating Disorders',
    forensic_psychology: 'Forensic Psychology',
    indigenous_first_nations: 'Indigenous & First Nations & Native Americans',
    life_transitions: 'Life Transitions',
    mindfulness: 'Mindfulness',
    obsessive: 'Obsessive Compulsive Disorder',
    post_traumatic: 'Post-Traumatic Stress Disorder',
    self_esteem: 'Self-Esteem',
    spirituality_faith: 'Spirituality/Faith',
    wellness: 'Wellness of Musculoskeletal System',

    acute: 'Acute and Chronic Medical Conditions',
    african: 'African American',
    autism: 'Autism Spectrum Disorder',
    clinical: 'Clinical Hypnosis',
    college_students: 'College Students',
    depression: 'Depression',
    emdr: 'EMDR',
    gender: 'Gender and sexual diversity',
    infertility: 'Infertility',
    health_men: 'Men’s Issues & Health',
    motivation: 'Motivation & Goal Achievement',
    parenting: 'Parenting',
    postpartum: 'Postpartum Depression',
    sexual_abuse: 'Sexual Abuse',
    sport: 'Sport Performance and Biofeedback',
    health_women: 'Women’s Issues & Health',

    recovery: 'Addictions/Recovery',
    management: 'Anger Management',
    disorder: 'Bipolar Disorder',
    clinical_supervision: 'Clinical Supervision',
    compassion: 'Compassion Fatigue & Burnout',
    diabetes: 'Diabetes',
    erectile: 'Erectile Dysfunction',
    grief: 'Grief',
    intimacy_sexual: 'Intimacy & Sexual Health',
    metabolic: 'Metabolic Syndrome',
    narcissism: 'Narcissism',
    pastors: 'Pastors',
    relationships: 'Relationships',
    sexual_addiction: 'Sexual Addiction',
    stress: 'Stress',
    performance_work: 'Work Issues/Performance',

    adhd: 'ADHD/ADD',
    anxiety: 'Anxiety',
    borderline: 'Borderline Personality Disorder',
    codependecy: 'Codependecy',
    coping_skills: 'Coping Skills',
    divorce: 'Divorce',
    family: 'Family',
    immigrant: 'Immigrant and Refugee Mental Health',
    lgbtqia: 'LGBTQIA',
    military_issues: 'Military Related Issues',
    obesity: 'Obesity',
    phobias: 'Phobias',
    schizophrenia: 'Schizophrenia',
    social_search: 'Social Justice/Search for Meaning',
    trauma_abuse: 'Trauma/Abuse',
    muscle_skeleton: 'Wellness of Musculoskeletal System',
    woman_issue: 'Women’s Issues & Health',
    work_issue: 'Work Issues/Performance',
};